### ISSUE TITLE
PLAYERBOT & SOLO-LFG

### ISSUE THREAD

**Issue by virgo77** [liyunfan1223/mod-playerbots#1005]
Hi Liyunfan123,

I'm trying to compile with your last updates, but I got an error at 98% :'(

I don't know if it's relevant on your specific branch, your module or whatever, but I got these errors:
```
[ 98%] Building CXX object modules/CMakeFiles/modules.dir/mod-transmog/src/Transmogrification.cpp.o
/home/acore/_PLAYERBOTS-SPP_/core/modules/mod-solo-lfg/src/Lfg_Solo.cpp:21:34: fatal error: only virtual member functions can be marked 'override'
   21 |     void OnLogin(Player* player) override
      |                                  ^~~~~~~~
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:6992: modules/CMakeFiles/modules.dir/mod-solo-lfg/src/Lfg_Solo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
18 warnings generated.
make[1]: *** [CMakeFiles/Makefile2:1063: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
Yes, on these lines, it speaks about 'Transmog', but it says also about 'Solo-LFG'.
So, I don't know if it's "Transmog" module that's causing the problem, or if it's "Solo LFG", or maybe your changes in the Playerbot Branch.
If you got time, can you check and tell me if it's fixable?
Thanks a lot for your time :)

Best Regards,
V.

**Comment by noisiver** [comment]
This is not related to playerbots but is an issue with the transmog module. As far as I know it has been fixed and you need to update the module on your end.

I'm closing this issue since it's not related to this module.

**Comment by virgo77** [comment]
ok thanks for your quick reply.

I just updated the Transmog Module (it was a fresh update on this morning), but the errors are still present.
Note that if i delete the 'override' option on lines 21 and 30 of this file "./core/modules/mod-solo-lfg/src/Lfg_Solo.cpp", the compilation entirely ends.
However, don't know about the possible bugs I can get in the game. ^^
Hope not!

Thanks :)

**Comment by Dreathean** [comment]
Seems like it’s an issue with the solo lfg module that needs updating then.
