### ISSUE TITLE
Chatter texts placeholder seems not working

### ISSUE THREAD

**Issue by Raz0r1337** [liyunfan1223/mod-playerbots#1682]
**Bug Description**
It seems as if the placeholder of the chatt texts are no longer exchanged with data.

For example, there is just %quest_link in the chat instead of the quest name.

**Commit Hash**
 AC-PB-Fork
b0f3de65f55cfd3f817a51c3c2fc23143321a89b PB

**How To Reproduce Bug**
Just look at the chat.
Idk if this is only present in the german language, but it should be on all languages.

**Expected Behavior**
Instead of %quest_link it has to be the name of the quest and so on.

**Screenshots**
<img width="745" height="71" alt="Image" src="https://github.com/user-attachments/assets/2323e818-c59f-408b-ae68-012612d2167b" />

**Modules**
mod-ah-bot
mod-quest-loot-party
mod-player-bot-level-brackets
mod-weekendbonus
mod-junk-to-gold
mod-desertation-warnings

**Playerbot Settings**
min-bots: 500
max-bots: 1000

**System**
OS: Linux Ubuntu Server 24.04.2
Hardware: enough ;-)

**Comment by privatecore** [comment]
Can you check id from `ai_playerbot_texts`?
```sql
select `id`,`text` from `ai_playerbot_texts` where `text_loc3` like 'Braucht jemand Hilfe bei%';
```

**Comment by Raz0r1337** [comment]
Offcourse,
Here's the output:

UPDATE `ai_playerbot_texts` SET `id`=396, `text`='Please spare some gold for me. You can buy %item_formatted_link for %cost_gold.' WHERE `id`=396;
UPDATE `ai_playerbot_texts` SET `id`=408, `text`='%other_name, I am up for %quest_links, I am in %zone_name right now' WHERE `id`=408;
UPDATE `ai_playerbot_texts` SET `id`=471, `text`='What did you say, %s?' WHERE `id`=471;
UPDATE `ai_playerbot_texts` SET `id`=495, `text`='%s you can\'t hear the dripping sarcasm in my text' WHERE `id`=495;
UPDATE `ai_playerbot_texts` SET `id`=521, `text`='7/10 would' WHERE `id`=521;
UPDATE `ai_playerbot_texts` SET `id`=524, `text`='yeah so what' WHERE `id`=524;

**Comment by noisiver** [comment]
How did that import to begin with?
```
`text`='%s you can't hear the dripping sarcasm in my text'
```
The apostrophe has to be escaped since it is inside a set of apostrophe
```
`text`='%s you can\'t hear the dripping sarcasm in my text'
```

**Comment by Raz0r1337** [comment]
Unfortunately, this is necessary because the German localization is being deleted due to some SQL update. So I reinstalled the original database without any updates, exported the text_loc3 column, and imported it into the updated database. I also created a PR for it and removed the German texts from the base file. 

The output I wrote above was copied 1:1 from HeidiSQL after I executed the command from privatecore.

**Comment by privatecore** [comment]
> Offcourse,
> Here's the output:

It seems like you did something wrong with HeidiSQL ;)

I wrote you a SELECT query that should return two fields from the table ai_playerbot_texts based on the condition where text_loc3 (German localization) is like 'Braucht jemand Hilfe bei%'. So, the output should be in output tab or something like that.

**Comment by privatecore** [comment]
Nvm, found your pull request and changes you are trying to make:
https://github.com/Raz0r1337/mod-playerbots/blob/master/data/sql/playerbots/updates/2025_09_28_00_ai_playerbot_german_texts.sql#L521

You are using wrong id to update:
```
+-----+-------+------------+
| id  | name  | text       |
+-----+-------+------------+
| 521 | reply | 7/10 would |
+-----+-------+------------+
```

**Comment by Raz0r1337** [comment]
Ok, thx.
I will care about this.

But how can that be?
I exported text_loc3 with the IDs from Heidi.
I used this SQL command:

SELECT `id`, `text_loc3`
FROM `acore_playerbots`.`ai_playerbot_texts`
ORDER BY `id`;

And then right click and export to UPDATE-SQL file.
Is there something wrong with it?

And my example screenshot is only a example. Not one of the placeholder was working.

**Comment by privatecore** [comment]
Are you tryin to restore these entries: https://github.com/liyunfan1223/mod-playerbots/blob/master/data/sql/playerbots/base/ai_playerbot_texts.sql ?

**Comment by Raz0r1337** [comment]
Exactly.
Because the text_loc3 column gets deleted if the server runs the SQL updates.

**Comment by Raz0r1337** [comment]
Let me guess.
There was an update at some point that added a few lines of text, and that's what caused the ID shift?

Because I exported the original base DB without this update. 🤦🤣

**Comment by privatecore** [comment]
Yep ;)
https://github.com/liyunfan1223/mod-playerbots/blob/master/data/sql/playerbots/updates/2024_08_07_00.sql

Do you need help with this, or do you now know how to restore those deleted entries?

**Comment by Raz0r1337** [comment]
Perfect. Thank you very much. ❤️

With this I can correct my PR.
And hopefully the server uses these placeholder again.

**Comment by Raz0r1337** [comment]
I think with this information, I'll be able to export everything correctly now.
Thanks again for the push in the right direction. 😅

**Comment by Raz0r1337** [comment]
Hm, This update "https://github.com/liyunfan1223/mod-playerbots/blob/master/data/sql/playerbots/updates/2024_08_07_00.sql" is precisely the reason why the German and almost all other localization was deleted from the database in the first place.

Shouldn't updates be designed to maintain and improve the existing functionality, rather than simply deleting everything that was there before?

**Comment by Raz0r1337** [comment]
It was actually just the wrong IDs. This problem has been resolved with my fix in the PR.

**Comment by kadeshar** [comment]
Can someone confirm that bug still exists after PR https://github.com/liyunfan1223/mod-playerbots/commit/1fb66e9d75c4eeb62aeb3405769d081bc3996577 was merged?

**Comment by privatecore** [comment]
It's not actually a bug https://github.com/liyunfan1223/mod-playerbots/issues/1682#issuecomment-3353756246 ;)
Can't comment on the German translation, but if you exported the `ai_playerbot_texts` table after all the pull requests, everything should be fine.

**Comment by kadeshar** [comment]
Bugged was that base file was updated without update script which means that people which create database before that change have other id's than people which creates after that change. And all last updates modifying database via id didnt worked correctly for people with new database.

**Comment by privatecore** [comment]
> Bugged was that base file was updated without update script

Wait, are you saying the ID numbers from the first script https://github.com/liyunfan1223/mod-playerbots/blob/master/data/sql/playerbots/base/ai_playerbot_texts.sql got changed by the update https://github.com/liyunfan1223/mod-playerbots/blob/master/data/sql/playerbots/updates/2024_08_07_00.sql  and now they don't match up, but they're supposed to?

**Comment by kadeshar** [comment]
No, this PR broke id order https://github.com/liyunfan1223/mod-playerbots/commit/b0ca0e85956ccf7d0177326a62c8bab9b5f4e70f and wasnt applied as a update script (only to base file). Which means that people before my fix had this table in 2 state depends when table was create (before of after this commit)

**Comment by privatecore** [comment]
Hmm, I see now. However, your PR still hasn't fixed the issue: the base file also needs to be updated with the new translations ;)

**Comment by kadeshar** [comment]
Tbh base + all previous updates are unimportant now because my update override that. Ofc i could update base file and delete update scripts but im not sure that is proper way.

**Comment by privatecore** [comment]
> Ofc i could update base file and delete update scripts but im not sure that is proper way.

Yep, it's kind of hard to fix all this mess now... Is it acceptable to change the content of previous SQL updates in light of repository code policy, or would it be better to proceed with fix updates?

**Comment by Raz0r1337** [comment]
YES, that was not a bug.

It happened because the placeholders were no longer in the correct line, as the IDs in the update files of the translations did not match the IDs in the database.

It's closed.
