### ISSUE TITLE
Worldserver.exe crash due to ACCESS_VIOLATION

### ISSUE THREAD

**Issue by DOKDOR** [liyunfan1223/mod-playerbots#1695]
**Bug Description**
3  crashes now due to ACCESS_VIOLATION. All time have been on empty player server. 4 real players on server total. All either use rndbot or altbot parties. 

**Commit Hash**
9d82a3567

**How To Reproduce Bug**
Run worldserver.exe for 14+ hours

**Expected Behavior**
No crash

**Screenshots**
N/A

**Modules**
mod-ghost-speed
mod-quick-respawn
mod-flightmaster-whistle
mod-dungeonmaster
mod-no-hearthstone-cooldown
mod-ah-bot
mod-autobalance
mod-rdf-expansion
mod-player-bot-level-brackets
mod-playerbots

**Playerbot Settings**
500 bots
AiPlayerbot.BotActiveAlone = 10
AiPlayerbot.botActiveAloneSmartScale = 1
AiPlayerbot.botActiveAloneSmartScaleWhenMinLevel = 1
AiPlayerbot.botActiveAloneSmartScaleWhenMaxLevel = 80

**System**
OS: Windows 10 Professional (Version 10.0, Build 19045)
Hardware:
Processor: Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
Number Of Processors: 4
Physical Memory: 33493436 KB (Available: 23496860 KB)
Commit Charge Limit: 38474172 KB

**Comment by DOKDOR** [comment]
Here are my crash logs. 

[9d82a356719b_worldserver.exe_\[29-9_15-59-52\].txt](https://github.com/user-attachments/files/22676954/9d82a356719b_worldserver.exe_.29-9_15-59-52.txt)
[9d82a356719b_worldserver.exe_\[3-10_1-44-37\].txt](https://github.com/user-attachments/files/22676953/9d82a356719b_worldserver.exe_.3-10_1-44-37.txt)
[9d82a356719b_worldserver.exe_\[3-10_1-42-25\].txt](https://github.com/user-attachments/files/22676955/9d82a356719b_worldserver.exe_.3-10_1-42-25.txt)

**Comment by Badgermilk0** [comment]
Don't have the technical skills to troubleshoot the crash logs - though my server current uptime is several days.
I have turned everything related to chat from bots, could you test that perhaps?

.# CHAT SETTINGS in the conf file.

**Comment by kadeshar** [comment]
Provide playerbots commit hash

**Comment by Celandriel** [comment]
Did the issue happen twice in a row 2 min apart?

**Comment by DOKDOR** [comment]
> Provide playerbots commit hash

Should be this one 55b58a2

> Did the issue happen twice in a row 2 min apart?

Yes

**Comment by hermensbas** [comment]
Thanks for bug report!

**Comment by kadeshar** [comment]
Server uptime is not way to reproduce bug
<img width="869" height="180" alt="Image" src="https://github.com/user-attachments/assets/fed17100-f7de-4b99-a1cc-35b4689fe17f" />

**Comment by DOKDOR** [comment]
> Server uptime is not way to reproduce bug

I have updated the bug report to include our talking from discord the other day.

**Comment by hermensbas** [comment]
> Server uptime is not way to reproduce bug <img alt="Image" width="869" height="180" src="https://private-user-images.githubusercontent.com/28183654/497571007-fed17100-f7de-4b99-a1cc-35b4689fe17f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk3MzgxMTMsIm5iZiI6MTc1OTczNzgxMywicGF0aCI6Ii8yODE4MzY1NC80OTc1NzEwMDctZmVkMTcxMDAtZjdkZS00Yjk5LWExY2MtMzViNDY4OWZlMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA2VDA4MDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjBlMDU4MWJhOGY5MjljNmRlMWJiYjMzODIwYWE2MjZjMGFjZWNmNGIyY2I0YTNjZjVhNzAyM2EwY2RlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i17O0cW0AnvRYjj8EG3rebPLY0-WI0hMNP11p0KbBsg">

Well not on itself no, but if its related to threading and combination with actors like real players invoking events on server side, the server uptime in right conditions could be decent test. With the "right conditions" i meanl where multiple, how more the better), real players actively playing the game and doing all kinds of interactions with bots. Adding, removing groups, create raid, extend raid just random various scenario's. That in combination with crash logs actually helps quite a lot i would say.

Its not a clean test sure, but decent enough to get general idea if its stabile or not, it might not be conclusive though but it does help.

**Comment by hermensbas** [comment]
You could try if https://github.com/liyunfan1223/mod-playerbots/pull/1708 has any positive impact in that regard. That being said i didnt have the time yet to test it other then basic tests.

**Comment by hermensbas** [comment]
Can you try if you see any difference when using the following code:

```bash
git clone https://github.com/hermensbas/mod-playerbots.git --branch=feature/removeFromGroup_replaced_with_worldpackets
```

Assuming you are using your server running bots and multiple real players.

**Comment by kadeshar** [comment]
Possible fix merged. Update module and confirm that crashes persist.

**Comment by DOKDOR** [comment]
Problem persists even with the new version. 

Using latest core and module. 

I have attached 2 more crash logs. The first seems to be empty (but gives timestamp). The second happened minutes later after my restart script kicked in. 

[6aef3aae5f26_worldserver.exe_\[16-10_22-42-54\].txt](https://github.com/user-attachments/files/22949770/6aef3aae5f26_worldserver.exe_.16-10_22-42-54.txt)
[6aef3aae5f26_worldserver.exe_\[16-10_22-44-53\].txt](https://github.com/user-attachments/files/22949771/6aef3aae5f26_worldserver.exe_.16-10_22-44-53.txt)

This time a player was online, in a party of 4 Altbots. Was walking around dalaran going to vendors. Nothing noteworthy when the crash occurred.

**Comment by noisiver** [comment]
The second one is not usable. Even though it was compiled with RelWithDebInfo I assume the .pdb files aren't in the same folder as the .exe files so the crash logs are worthless.

<img width="951" height="387" alt="Image" src="https://github.com/user-attachments/assets/4d0c5d6e-fbe8-4539-a497-2cc108e81bb3" />

**Comment by DOKDOR** [comment]
I followed the standard install instructions from the azerothcore website, but replaced with the Playerbots branch. 

How can I generate usable crash logs? 
Which .pdb are needed to be moved and I can do that?

Also just had another crash. Again an empty crash log. 

[6aef3aae5f26_worldserver.exe_\[16-10_22-59-3\].txt](https://github.com/user-attachments/files/22950021/6aef3aae5f26_worldserver.exe_.16-10_22-59-3.txt)

**Comment by noisiver** [comment]
They are generated in the same folder as worldserver.exe when the project is built. `worldserver.pdb` etc

**Comment by DOKDOR** [comment]
I don’t see those .pdb files in my folder with my .exes. Is there something I’m missing from cmake or VS that I need to change to get them included?

Again I followed the install instructions verbatim from the installation website. If it’s default I’m not sure why they are not included.

**Comment by DOKDOR** [comment]
> This time a player was online, in a party of 4 Altbots. Was walking around dalaran going to vendors. Nothing noteworthy when the crash occurred.

Player finally got back to me. Apparently they were trying to dismiss the altbot party using the multibot plugin while in dalaran. When they right clicked on the altbot frame in the plugin the server crashed the first time. The second time they were not back in the games yet. The third time they had just logged in. 

When I get a chance, and once I have the right files to generate proper logs, I’ll try to recreate (or have the player try to recreate)

**Comment by DOKDOR** [comment]
I have fully re-built the core+modules and the .pdb files are now where they should be. I’ll get the player to try and do what they did yesterday, plus I’ll do some testing and report back if I get another crash.
