### ISSUE TITLE
Bots dont join Dungeon Finder

### ISSUE THREAD

**Issue by brunolopes1996** [liyunfan1223/mod-playerbots#262]
**Describe the bug**
The bots are not joinining dungeon finder, I have the settings enabled on playerbots.conf

**Commit hash**
cloned and compiled fresh on 6-6-2024

**To Reproduce**
Start the server
log in a character that is lvl 15 or more
queue dungeon finder
no dungeon queue will pop 

**Expected behavior**

Bots would join the dungeonfinder group

**Desktop (please complete the following information):**
Windows

**Comment by sanpedrox2** [comment]
same :(

**Comment by brian8544** [comment]
This does not work on the original project either, don't expect this to change any time soon. However lfg command could be implemented. 

https://github.com/search?q=repo%3Acmangos%2Fplayerbots+lfg&type=commits

**Comment by BenWagner-UX** [comment]
fixed in: PR #306

**Comment by Caffarius** [comment]
I had pulled in the activation from #306, and while the server acknowledged that bots were queuing for LFG in the logs I could sit for over an hour and still not get a match. I'm pulling #330 to give it another go; really looking forward to not assembling a team manually! That's a huge step forward for the module.

We all appreciate the work everyone's putting into this. It's truly starting to come together.

**Comment by BenWagner-UX** [comment]
> I had pulled in the activation from #306, and while the server acknowledged that bots were queuing for LFG in the logs I could sit for over an hour and still not get a match. I'm pulling #330 to give it another go; really looking forward to not assembling a team manually! That's a huge step forward for the module.
> 
> We all appreciate the work everyone's putting into this. It's truly starting to come together.

Try these aswell:

https://github.com/liyunfan1223/azerothcore-wotlk/pulls 13+14

**Comment by Caffarius** [comment]
> Try these aswell:
> 
> https://github.com/liyunfan1223/azerothcore-wotlk/pulls 13+14

That does the trick. It took seven attempts for LFG to build a group - but it did finally do it! A DPS left the group immediately upon entrance but the system found a replacement. Not the ideal situation but totally livable considering this didn't work at all previously (and I've had worse occurrences in retail).

I'm never building a dungeon group again. 🥳

**Comment by BenWagner-UX** [comment]
> > Try these aswell:
> > https://github.com/liyunfan1223/azerothcore-wotlk/pulls 13+14
> 
> That does the trick. It took seven attempts for LFG to build a group - but it did finally do it! A DPS left the group immediately upon entrance but the system found a replacement. Not the ideal situation but totally livable considering this didn't work at all previously (and I've had worse occurrences in retail).
> 
> I'm never building a dungeon group again. 🥳

It just simulates a real world scenario ;p

**Comment by Dreathean** [comment]
Closing as this should be fixed now, thanks @BenWagner-UX! By the way, are you on the playerbot discord? If not would love to have you join in on development discussions there!

**Comment by mw108** [comment]
This doesn't seem to work for me here. I'm using the latest commit.

When I queue for LFG as DD I instantly get an invite to the dungeon but then I'm sitting there alone and nothing happens. No bots are joining. There are a lot of bots around my level online who could join though.

`AiPlayerbot.RandomBotJoinLfg` is enabled.

```
# Enable LFG for random bots
AiPlayerbot.RandomBotJoinLfg = 1
```

Am I missing something or am I doing something wrong?

**Comment by shenkai4257** [comment]
这个问题可以关闭了吧，目前测试随机地下城是没有问题的，如果遇到长时间排不进去的，可以在playerbot的配置文件里头多设置一些随机机器人数量，确保每个等级范围的机器人数量足够就可以了。

**Comment by ratliff641** [comment]
I've noticed this issue, though it only seems to be the bots that are pvp flagged. If they aren't, they can join just fine.
Now, following a wipe or a death that isn't rezzed, that's a different story. I often have to kick and requeue (if I'm the lead). If not, I often have to leave the dungeon altogether. Sometimes when I port back, they'll be there. Sometimes not. When that happens I drop group and try again later.
I've noticed a lot fewer issues if I pre-form the party myself as lead, set loot to free for all, and go to town.

**Comment by AoifeHughes** [comment]
> This doesn't seem to work for me here. I'm using the latest commit.
> 
> When I queue for LFG as DD I instantly get an invite to the dungeon but then I'm sitting there alone and nothing happens. No bots are joining. There are a lot of bots around my level online who could join though.
> 
> `AiPlayerbot.RandomBotJoinLfg` is enabled.
> 
> ```
> # Enable LFG for random bots
> AiPlayerbot.RandomBotJoinLfg = 1
> ```
> 
> Am I missing something or am I doing something wrong?
> 
> [YouTube Video](https://youtu.be/nBGftct_bN8)

I've the exact same issue - has there ever been a confirmed fix for this?

**Comment by Celandriel** [comment]
Likely a recent bug that was introduced.
Working on it.

**Comment by AoifeHughes** [comment]
Interesting, I just checked with BGs and they work fine with bots joining. Its just the dungeon finder.
